# Generated by Django 3.0.5 on 2020-05-24 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='model',
        ),
    ]
